name: "test build"

on:
  push:
    branches: [ "master", "develop", "feature/*", "bugfix/*" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup_java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: run_tests
        run: ./gradlew test
