name: "build debug apk"

on:
  push:
    branches: [ "develop" ]
    tags: [ "d_*" ]

jobs:
  buildDebug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: prepare_vars
        id: prepare
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=tag_short::${GITHUB_REF##*/}"

      - name: setup_java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: assemble
        run: ./gradlew assembleDebug

      - name: upload
        uses: wei/curl@v1.1.1
        env:
          APP_NAME: f1dashboard
          APP_VERSION: ${{ steps.prepare.outputs.tag_short }}-${{ steps.prepare.outputs.sha_short }}
          URL: https://nexus.n1ks.it
          USERNAME: ${{ secrets.NEXUS_USERNAME }}
          PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        with:
          args: -u $USERNAME:$PASSWORD "$URL//service/rest/v1/components?repository=debugpub" -F "raw.directory=$APP_NAME" -F "raw.asset1=@app/build/outputs/apk/debug/app-debug.apk" -F "raw.asset1.filename=$APP_NAME-$APP_VERSION.apk"
